import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import styles from '@/styles/Home.module.css'
import $ from 'jquery';
import { useEffect } from 'react'


const inter = Inter({ subsets: ['latin'] })




export default function Home() {

  useEffect(() => {
    // Run this code only on the client
    $(function () {
      $('.q-flex').click(function () {
        if ($(this).siblings('.answer').is(':visible')) {
          $('.answer').slideUp();
          console.log("open")
        } else {
          $('.answer').slideUp();
          $(this).siblings('.answer').slideDown();
          console.log("close")
        }
      })
    })

    $('#menuIcon').click(function () {
      $('.mobile-nav').slideDown();
      $(this).hide();
      $('#closeIcon').fadeIn();
    })
    $('#closeIcon').click(function () {
      $('.mobile-nav').slideUp();
      $(this).hide();
      $('#menuIcon').fadeIn();
    })
  }, []);

  

 
  return (
    <>
      <Head>
        <title>Control Resell</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header id="about" style={{ backgroundImage: `url('/images/hero-bg.png')`, backgroundSize: 'cover' }}>

        <nav>
          <div className="container">
            <Link href="index.html" className="logo">
              <img src='/images/logo.png' alt="Logo" />
            </Link>
            <ul className="navbar-nav hide-mobile">
              <li><Link className="nav-link" href="/">Accueil</Link></li>
              <li><Link className="nav-link" href="/">Fonctionnalités</Link></li>
              <li><Link className="nav-link" href="/">Prix</Link></li>
              <li><Link className="nav-link" href="/Blog">Blog</Link></li>
            </ul>
            <ul className="btn-nav hide-mobile">
              <li>
                <Link href="/" className="btn">Inscrivez-vous maintenant !</Link>
              </li>
            </ul>
            <div className="menu">
              <img src='/images/menu.png' alt="Menu" id="menuIcon" />
              <img src="./images/close.png" alt="Menu" id="closeIcon" />
            </div>
            <div className="show-mobile mobile-nav">
              <ul className="navbar-nav">
                <li><Link className="nav-link" href="/">Accueil</Link></li>
                <li><Link className="nav-link" href="/">Fonctionnalités</Link></li>
                <li><Link className="nav-link" href="/">Prix</Link></li>
                <li><Link className="nav-link" href="/">Blog</Link></li>
              </ul>
              <ul className="btn-nav">
                <li>
                  <Link href="/" className="btn">Inscrivez-vous
                    maintenant !</Link>
                </li>
              </ul>
            </div>
          </div>
        </nav>
        <div className="container">
          <div className="hero-sec">
            <div className="hero-left">
              <h1 className="hero-title">Achats reventes <br />comme un pro
                !</h1>
              <p className="hero-desc">
                Optimisez votre achats revente grâce à <br />notre
                application mobile. Gérez vos stocks, <br />prix et
                bénéfices en un clin d'œil !
              </p>
            </div>
            <div className="hero-right text-center">
              <img src="./images/hero-phone.png" alt="Hero Image"
                className="hero-Image" />
            </div>
          </div>
        </div>
      </header>
      <main>
        <section id="functionalities">
          <div className="container">
            <div className="sec-flex sec-flex1">
              <div className="f-right">
                <div className="f-content">
                  <h2 className="sec-title">Gérez facilement votre
                    inventaire</h2>
                  <p className="sec-desc">Ne perdez jamais le fil de
                    vos
                    achats et ventes. Avec notre application
                    mobile,
                    suivez votre inventaire en temps réel,
                    gardez
                    une trace de chaque article et gérez
                    efficacement vos stocks.</p>
                </div>
              </div>
              <div className="f-left text-center animation-cont">
                <img src="/images/animation_placeholder.png"
                  alt="Animation" className="animation" />
              </div>
            </div>

            <div className="sec-flex sec-flex2">
              <div className="f-right">
                <div className="f-content f-content2">
                  <h2 className="sec-title">Suivez vos gains et
                    dépenses</h2>
                  <p className="sec-desc">Avec notre outil d'analyse
                    des bénéfices et dépenses, gardez une trace
                    de toutes vos transactions et obtenez une
                    vue d'ensemble de votre activité de revente.
                    Identifiez les articles les plus rentables
                    et prenez des décisions éclairées pour votre
                    buisness.</p>
                  <Link href="/" className="btn">Inscrivez-vous
                    maintenant !</Link>
                </div>
              </div>
              <div className="f-left">
                <div className="c-flex">
                  <div className="card card-sm">
                    <p className="c-desc">Bénéfice</p>
                    <h2 className="c-price">3,235 &euro;</h2>
                  </div>
                  <div className="card card-sm">
                    <p className="c-desc">En cours</p>
                    <h2 className="c-price">267 &euro;</h2>
                  </div>
                </div>
                <div className="card card-lg">
                  <img src="/images/Chart.png" alt="Chart"
                    className="chart" />
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="price" id="price">
          <div className="container">
            <h2 className="sec-title2 text-center">
              Un service exceptionnel, <span className="cyan">au juste
                prix</span>
            </h2>
            <p className="sec-desc2 text-center">Commencez avec notre plan
              gratuit et
              passez au premium lorsque vous grandissez.</p>
            <div className="price-container">
              <div className="pc-flex">
                <div className="card p-card">
                  <div className="text-center">
                    <h3 className="pc-title">Free</h3>
                    <h2 className="pc-price">0&euro;<span
                      className="sm">/m</span></h2>
                    <p className="pc-desc">Suivi jusqu'à 10 articles
                      pour commencer doucement</p>
                    <Link href="/" className="btn btn-lg">Inscrivez-vous
                      maintenant !</Link>
                  </div>
                  <div className="features">
                    <ul>
                      <li className="green"> <img src='/images/check-green.png' alt="Logo" />Suivi d'article limité</li>
                      <li className="green"> <img src='/images/check-green.png' alt="Logo" />Analyse des bénéfices
                        et pertes</li>
                      <li className="green"> <img src='/images/check-green.png' alt="Logo" />Estimations prix du
                        marché</li>
                      <li className="green"> <img src='/images/check-green.png' alt="Logo" />Alertes de tendances
                        du marché</li>
                      <li className="grey"> <img src='/images/check-grey.png' alt="Logo" /> Statistiques sur les
                        ventes et les bénéfices</li>
                      <li className="grey"> <img src='/images/check-grey.png' alt="Logo" />Description automatique</li>
                      <li className="grey"> <img src='/images/check-grey.png' alt="Logo" />Support prioritaire</li>
                    </ul>
                  </div>
                </div>

                <div className="card p-card">
                  <div className="text-center">
                    <h3 className="pc-title">Premium</h3>
                    <h2 className="pc-price">8&euro;<span
                      className="sm">/m</span></h2>
                    <p className="pc-desc">Suivi illimité et de
                      fonctionnalités avancées pour améliorer
                      vos ventes</p>
                    <Link href="/" className="btn btn-lg">Inscrivez-vous
                      maintenant !</Link>
                  </div>
                  <div className="features">
                    <ul>
                      <li className="green"> <img src='/images/check-green.png' alt="Logo" />Suivi d'article limité</li>
                      <li className="green"> <img src='/images/check-green.png' alt="Logo" />Analyse des bénéfices
                        et pertes</li>
                      <li className="green"> <img src='/images/check-green.png' alt="Logo" />Estimations prix du
                        marché</li>
                      <li className="green"> <img src='/images/check-green.png' alt="Logo" />Alertes de tendances
                        du marché</li>
                      <li className="green"> <img src='/images/check-green.png' alt="Logo" />Statistiques sur les
                        ventes et les bénéfices</li>
                      <li className="green"> <img src='/images/check-green.png' alt="Logo" />Description
                        automatique</li>
                      <li className="green"> <img src='/images/check-green.png' alt="Logo" />Support prioritaire</li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        <section className="faq" id="faq" style={{ backgroundImage: `url('/images/lines-bg.png')`, backgroundSize: 'cover' }}>
          <div className="container">
            <div className="w-70 text-center">
              <h2 className="sec-title2">
                <span className="cyan">Questions</span> fréquemment
                posées
              </h2>
              <p className="sec-desc2">Si vous n'êtes pas sûr que
                ControlResell
                convient à vos besoins, ne vous inquiétez pas. Nous
                sommes là pour expliquer tout ce que vous pourriez
                vouloir savoir.</p>
            </div>
            <div className="faqs">
              <div className="qa">
                <div className="q-flex">
                  <h4 className="ques">Qu'est-ce que
                    ControlResell ?</h4>
                  <span className="signs"><img src="/images/plus.png"
                    alt="Plus" className="plus" height="20" /></span>
                </div>
                <div className="answer">
                  <p>Lorem ipsum, dolor sit amet consectetur
                    adipisicing elit. Distinctio repellendus
                    quidem doloribus, illo quam eveniet
                    explicabo animi recusandae vero rerum
                    veritatis maiores, perspiciatis accusamus
                    sit ad sed voluptate quae praesentium!</p>
                </div>
              </div>
              <div className="qa">
                <div className="q-flex">
                  <h4 className="ques">Comment fonctionne
                    ControlResell ?</h4>
                  <span className="signs"><img src="/images/plus.png"
                    alt="Plus" className="plus" height="20" /></span>
                </div>
                <div className="answer">
                  <p>Lorem ipsum, dolor sit amet consectetur
                    adipisicing elit. Distinctio repellendus
                    quidem doloribus, illo quam eveniet
                    explicabo animi recusandae vero rerum
                    veritatis maiores, perspiciatis accusamus
                    sit ad sed voluptate quae praesentium!</p>
                </div>
              </div>
              <div className="qa">
                <div className="q-flex">
                  <h4 className="ques">Quelle est la limite d'articles
                    pour la version gratuite ?</h4>
                  <span className="signs"><img src="/images/plus.png"
                    alt="Plus" className="plus" height="20" /></span>
                </div>
                <div className="answer">
                  <p>Lorem ipsum, dolor sit amet consectetur
                    adipisicing elit. Distinctio repellendus
                    quidem doloribus, illo quam eveniet
                    explicabo animi recusandae vero rerum
                    veritatis maiores, perspiciatis accusamus
                    sit ad sed voluptate quae praesentium!</p>
                </div>
              </div>
              <div className="qa">
                <div className="q-flex">
                  <h4 className="ques">Puis-je annuler mon abonnement
                    à tout moment ?</h4>
                  <span className="signs"><img src="/images/plus.png"
                    alt="Plus" className="plus" height="20" /></span>
                </div>
                <div className="answer">
                  <p>Lorem ipsum, dolor sit amet consectetur
                    adipisicing elit. Distinctio repellendus
                    quidem doloribus, illo quam eveniet
                    explicabo animi recusandae vero rerum
                    veritatis maiores, perspiciatis accusamus
                    sit ad sed voluptate quae praesentium!</p>
                </div>
              </div>
              <div className="qa">
                <div className="q-flex">
                  <h4 className="ques">Comment puis-je participer à la
                    beta ?</h4>
                  <span className="signs"><img src="/images/plus.png"
                    alt="Plus" className="plus" height="20" /></span>
                </div>
                <div className="answer">
                  <p>Lorem ipsum, dolor sit amet consectetur
                    adipisicing elit. Distinctio repellendus
                    quidem doloribus, illo quam eveniet
                    explicabo animi recusandae vero rerum
                    veritatis maiores, perspiciatis accusamus
                    sit ad sed voluptate quae praesentium!</p>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
      <footer>
        <div className="container">
          <div className="fm-flex">
            <div className="footer-info">
              <Link href="index.html" className="logo"><img
                src="./images/logo-green.png" alt="Logo" /></Link>
              <p className="ft-desc">Copyright © 2020 ControlResell LLC.
                Tous droits réservé</p>
            </div>
            <div className="footer-nav">
              <div className="ft-col">
                <ul>
                  <li><Link href="/" className="nav-link">Team</Link></li>
                  <li><Link href="/" className="nav-link">Press</Link></li>
                  <li><Link href="/" className="nav-link">Prix</Link></li>
                </ul>
              </div>
              <div className="ft-col">
                <ul>
                  <li><Link href="/" className="nav-link">Services</Link></li>
                  <li><Link href="/" className="nav-link">Project</Link></li>
                  <li><Link href="/" className="nav-link">Affiliate</Link></li>
                </ul>
              </div>
              <div className="ft-col">
                <ul>
                  <li><Link href="/" className="nav-link">Terms of use</Link></li>
                  <li><Link href="/" className="nav-link">Privacy Policy</Link></li>
                  <li><Link href="/" className="nav-link">Contact us</Link></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </footer>
    </>
  )
}
